# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

version: 2

# Personal info
name: Ahmed Mahmoud Abd-Elmouty
title: Network Engineer
email: ahmedmahmoud2712001@gmail.com
phone: +201016383187
linkedin_username: ahmed-mahmoud-d27

# Dark Mode
darkmode: false

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I am a fresh graduate in network engineering, passionate about technology and ready to apply my skills in real-world settings.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Attendance Management System
        description: |
          Developed an Android app to track student attendance using QR codes.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Redcon for Construction
        sub_title: Survey Specialist
        caption: 2023

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Tanta University
        sub_title: Bachelor's Degree in Computer Science
        caption: 2023

  - title: Certifications
    layout: list
    content:
      - layout: top-right
        title: CCNA (Cisco Certified Network Associate)
        caption: 2024

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
